apiVersion: v1
kind: ConfigMap
metadata:
  name: web-content-v1
  namespace: default
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>Страница из nginx v1 </title>
    </head>
    <body>
      <h1>Привет от Kubernetes!</h1>
    </body>
    </html>
    
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: web-content-v2
  namespace: default
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>Страница из nginx v2 </title>
    </head>
    <body>
      <h1>Привет от Kubernetes!</h1>
    </body>
    </html>