---
apiVersion: v1
kind: Service
metadata:
  name: service-nginx-v1
spec:
  selector:
    app: nginx-01
  ports:
    - name: nginx
      protocol: TCP
      port: 9090
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: service-nginx-v2
spec:
  selector:
    app: nginx-02
  ports:
    - name: nginx
      protocol: TCP
      port: 9191
      targetPort: 80