apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.lavels }}{{ .Values.service.name }}
spec:
  selector:
    app: {{ .Values.labels }}
  ports:
    - name: {{ .Values.labels }}
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetport }}