name: deployment-myapp-test
labels: nginx-v1
replica_count: 1
image:
  name: nginx
  tag: "1.21.1"
content_name: web-content-v1
service:
  name: service-v1
  port: 9001
  targetport: 80

ingress:
  name: ingress
  enabled: true

appversion: 1.16.1