apiVersion: v1
kind: ConfigMap
metadata:
  name: web-content
  namespace: default
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>Страница из ConfigMap</title>
    </head>
    <body>
      <h1>Привет от Kubernetes!</h1>
    </body>
    </html>
    
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: multitool-env
  namespace: default
data:
  HTTP_PORT: "8080"
