---
apiVersion: v1
kind: Service
metadata:
  name: service-backend
  namespace: app
spec:
  selector:
    app: backend
  ports:
    - name: multitool
      protocol: TCP
      port: 9090
      targetPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: service-frontend
  namespace: app
spec:
  selector:
    app: frontend
  ports:
    - name: multitool
      protocol: TCP
      port: 9191
      targetPort: 8181
---
apiVersion: v1
kind: Service
metadata:
  name: service-cache
  namespace: app
spec:
  selector:
    app: cache
  ports:
    - name: multitool
      protocol: TCP
      port: 9292
      targetPort: 8282